management:
  server:
    port: 9000
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      enabled: true
      cache:
        time-to-live: 10000ms
    loggers:
      enabled: true

spring:
  application:
    name: Memo
  security:
    user:
      name: memo_admin
  datasource:
    host: localhost
    port: 5432
    database: memo
    username: postgres
    password: postgres
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?autoReconnect=true
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: /db/changelog/changelog-master.xml